name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  build and deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ci-cd-project .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag ci-cd-project:latest mukul7661/ci-cd-project
          docker push mukul7661/ci-cd-project

      # - name: Run tests
      #   run: npm test
